spring.application.name=Spring_Practice

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
jwt.secret=THIS_IS_A_DEMO_SECRET_KEY_FOR_LEARNING_PURPOSES_ONLY_123456789
jwt.expiration=86400000
