CREATE TABLE department (
id BIGSERIAL PRIMARY KEY,
name VARCHAR(100) NOT NULL UNIQUE);


CREATE TABLE student (
id BIGSERIAL PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(150) NOT NULL UNIQUE,
level INT NOT NULL,
department_id BIGINT NOT NULL,
created_at TIMESTAMP NOT NULL
updated_at TIMESTAMP NOT NULL

CONSTRAINT student_department_fk
FOREIGN KEY ()department_id)
REFERENCE  department(id);

